---
version: '3'
services:
  jenkins:
    build:
      context: ./docker
      args:
        docker_gid: 50
    ports:
      - '127.0.0.1:8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - ./data:/var/jenkins_home
