pipeline {
  agent any
  environment {
    HELLO = "world"
  }
  stages {
    stage("Build") {
      steps {
        sh 'echo Hello!'
      }
    }
  }
  post {
    always {
      deleteDir()
    }
  }
}